name: Pytest Python Testing
on: 
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Server/requirements.txt
      - name: Test with pytest
        run: |
            pytest --cov-report term-missing --cov     
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: UnitTestingPython
          name: codecov-umbrella
          verbose: true
