# workflow name
name: ReactTesting

# execute on events
on: push

# jobs to run
jobs:
  
  # install dependencies and run test command
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      # 1: setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # 2: Checkout repository in the CWD
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
        
      # 3: install NPM dependencies
      - name: Install dependencies
        run: |
          cd Client
          npm install
      
      # 4: run test command
      - name: Run test command
        run: |
          cd Client
          npm run test
